# Generated by Django 5.1.5 on 2025-01-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileEducationuser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('college', models.TextField()),
                ('speciality', models.TextField()),
                ('year_of_study', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'profile_educationuser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfilePersonalquality',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quality', models.TextField()),
                ('link', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'profile_personalquality',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfilePersonalqualityvalidator',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'profile_personalqualityvalidator',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfilePlaceofworkuser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company', models.TextField()),
                ('position', models.TextField()),
                ('work_period', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'profile_placeofworkuser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileProfile',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('tg_nick', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('date_of_birth', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('token', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'profile_profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileProfilevalidator',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'profile_profilevalidator',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'profile_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileUseravatar',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('avatar', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'profile_useravatar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'profile_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileUserskill',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=100)),
                ('skill_type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'profile_userskill',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileUserspecialization',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('specialization', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'profile_userspecialization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'profile_user_user_permissions',
                'managed': False,
            },
        ),
    ]
