# Generated by Django 5.1.5 on 2025-01-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_fields_field_type_fields_search_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='field_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='fields',
            name='field_type',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='fields',
            name='model_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='fields',
            name='search_weight',
            field=models.FloatField(blank=True, default=1),
        ),
    ]
