# Generated by Django 5.1.5 on 2025-01-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_fields_field_name_alter_fields_field_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='field_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
