# Generated by Django 5.1.5 on 2025-02-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_alter_fields_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fields',
            name='mult_search_type',
            field=models.CharField(choices=[('ANY', 'Хотя бы одно качество входит в поисковый запрос'), ('ALL', 'Есть все качества из поискового запроса')], default='ANY', max_length=3),
        ),
        migrations.AddField(
            model_name='fields',
            name='search_type',
            field=models.CharField(choices=[('EQUAL', 'Совпадение'), ('SUBSTR', 'Поиск подстроки')], default='EQUAL', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='fields',
            constraint=models.UniqueConstraint(fields=('model_name', 'field_name'), name='unique_model_and_field_name'),
        ),
    ]
