# Generated by Django 5.1.5 on 2025-02-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_fields_mult_search_type_fields_search_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='search_type',
            field=models.CharField(choices=[('EQUAL', 'Совпадение'), ('SUBSTR', 'Поиск подстроки'), ('AGE', 'Попадание д.р. в нужный диапазон возрастов')], default='EQUAL', max_length=10),
        ),
    ]
