# Generated by Django 5.1.5 on 2025-02-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_alter_fields_search_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(blank=True, max_length=32, unique=True)),
                ('search_enabled', models.BooleanField(default=True)),
                ('search_weight', models.FloatField(blank=True, default=1)),
                ('search_type', models.CharField(choices=[('EQUAL', 'Совпадение'), ('SUBSTR', 'Поиск подстроки'), ('AGE', 'Попадание д.р. в нужный диапазон возрастов')], default='EQUAL', max_length=10)),
                ('mult_search_type', models.CharField(choices=[('ANY', 'Хотя бы одно качество входит в поисковый запрос'), ('ALL', 'Есть все качества из поискового запроса')], default='ANY', max_length=3)),
            ],
        ),
    ]
