# Generated by Django 5.1.5 on 2025-02-01 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_searchparams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchparams',
            old_name='search_enabled',
            new_name='enabled',
        ),
        migrations.RenameField(
            model_name='searchparams',
            old_name='param_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='searchparams',
            old_name='search_weight',
            new_name='weight',
        ),
    ]
