# Generated by Django 5.1.5 on 2025-02-07 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_searchparams_priority'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fields',
        ),
    ]
