# Generated by Django 5.1.5 on 2025-02-07 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_delete_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchparams',
            name='mult_search_type',
        ),
        migrations.RemoveField(
            model_name='searchparams',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='searchparams',
            name='search_type',
        ),
    ]
